---
- hosts: all
  become: true
  vars:
     fstab_host_pattern: "serverA|rkanserverB|serverC"

  tasks:
    - name: Obtener lista de puntos de montaje que coincidan con el source indicado
      shell: mount -l|grep nfs |egrep '{{ fstab_host_pattern }}' | awk '{print $3}'
      register: mount_output

    - name: Mostrar los puntos de montaje encontrados
      debug:
        msg: "En {{ inventory_hostname }}, se encontraron estos puntos de montaje: {{ mount_output.stdout_lines }}"
      when: mount_output.stdout_lines | length > 0

    - name: Desmontar puntos de montaje detectados.
      command: umount {{ item }}
      with_items: "{{ mount_output.stdout_lines }}"
      when: mount_output.stdout_lines | length > 0
      ignore_errors: yes
