- name: lpfc link down event
  hosts: all
  become: yes
  tasks:
    - block:
        - name: Get server type
          ansible.builtin.command: /usr/sbin/dmidecode -s system-manufacturer
          register: server_type
          changed_when: false

        - name: Verify if server is 'Virtual'
          ansible.builtin.debug:
            msg: "VMware, Inc."
          when: server_type.stdout == "VMware, Inc."

        - name: Get current status of HBAs
          ansible.builtin.shell: "cat /sys/class/fc_host/host*/port_state || echo 'No HBAs'"
          register: hba_port_state
          changed_when: false
          failed_when: false
          when: server_type.stdout != "VMware, Inc."

        - name: Check if any HBA is in Linkdown
          ansible.builtin.set_fact:
            hba_state: "{{ 'failure' if ('Linkdown' in hba_port_state.stdout | regex_findall('Linkdown')) else 'success' }}"
          when: server_type.stdout != "VMware, Inc."

        - name: Set success variable
          ansible.builtin.set_fact:
            status: "{{ hba_state }}"
          when: server_type.stdout != "VMware, Inc."

      rescue:
        - name: Set failure variable in case of any error
          ansible.builtin.set_fact:
            status: "failure"

    - name: Mostrar estado final de las HBAs
      ansible.builtin.debug:
        msg: "El estado de las HBAs es: {{ status }}"
      when: server_type.stdout != "VMware, Inc."
